<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration for UPI Transactions table
 * Stores all UPI Intent payment records
 * 
 * Status Flow:
 * initiated → success_unconfirmed → settled
 *          → pending
 *          → failed / cancelled / expired
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('upi_transactions', function (Blueprint $table) {
            $table->id();
            
            // Unique payment reference (generated by system)
            $table->string('payment_ref', 50)->unique();
            
            // Order reference
            $table->unsignedBigInteger('order_id');
            $table->foreign('order_id')->references('id')->on('orders')->onDelete('cascade');
            
            // Store reference
            $table->unsignedBigInteger('store_id')->nullable();
            $table->foreign('store_id')->references('id')->on('stores')->onDelete('set null');
            
            // Delivery man who initiated
            $table->unsignedBigInteger('delivery_man_id')->nullable();
            $table->foreign('delivery_man_id')->references('id')->on('delivery_men')->onDelete('set null');
            
            // Payment details
            $table->decimal('amount', 12, 2);
            $table->string('upi_id', 100)->nullable()->comment('Merchant UPI ID');
            $table->string('merchant_name', 100)->nullable();
            
            // UPI Response data from app
            $table->string('txn_id', 50)->nullable()->comment('UPI Transaction ID from bank');
            $table->string('approval_ref_no', 50)->nullable()->comment('Bank approval reference');
            $table->string('response_code', 10)->nullable()->comment('UPI response code');
            $table->string('upi_app', 50)->nullable()->comment('App used: GPay, PhonePe, Paytm, BHIM');
            
            // Bank reconciliation reference
            $table->string('bank_reference', 50)->nullable()->comment('Bank statement reference after reconciliation');
            
            /**
             * Status values:
             * - initiated: Payment request created
             * - pending: Payment submitted but not confirmed
             * - success_unconfirmed: User confirmed success (NOT bank confirmed)
             * - settled: Bank confirmed after reconciliation
             * - failed: Payment failed
             * - cancelled: User cancelled
             * - expired: Payment request expired
             */
            $table->string('status', 25)->default('initiated');
            
            // Timestamps for tracking
            $table->timestamp('initiated_at')->nullable();
            $table->timestamp('confirmed_at')->nullable()->comment('When user confirmed payment');
            $table->timestamp('settled_at')->nullable()->comment('When bank reconciliation done');
            $table->timestamp('failed_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            
            // Who confirmed the payment
            $table->unsignedBigInteger('confirmed_by')->nullable()->comment('Delivery man who confirmed');
            
            // Additional notes
            $table->text('notes')->nullable();
            
            // Standard timestamps
            $table->timestamps();
            
            // Indexes for faster queries
            $table->index('order_id');
            $table->index('store_id');
            $table->index('delivery_man_id');
            $table->index('status');
            $table->index('txn_id');
            $table->index('created_at');
            $table->index(['status', 'created_at']); // For reports
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('upi_transactions');
    }
};	